// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: expense/expenses.proto

package finance_tracker_proto_files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Expense_CreateExpense_FullMethodName = "/Expense/CreateExpense"
	Expense_GetExpenses_FullMethodName   = "/Expense/GetExpenses"
	Expense_DeleteExpense_FullMethodName = "/Expense/DeleteExpense"
	Expense_UpdateExpense_FullMethodName = "/Expense/UpdateExpense"
)

// ExpenseClient is the client API for Expense service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExpenseClient interface {
	CreateExpense(ctx context.Context, in *CreateExenseRequest, opts ...grpc.CallOption) (*CreateExpenseResponse, error)
	GetExpenses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetExpensesResponse, error)
	DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, opts ...grpc.CallOption) (*DeleteExpenseResponse, error)
	UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*UpdateExpenseResponse, error)
}

type expenseClient struct {
	cc grpc.ClientConnInterface
}

func NewExpenseClient(cc grpc.ClientConnInterface) ExpenseClient {
	return &expenseClient{cc}
}

func (c *expenseClient) CreateExpense(ctx context.Context, in *CreateExenseRequest, opts ...grpc.CallOption) (*CreateExpenseResponse, error) {
	out := new(CreateExpenseResponse)
	err := c.cc.Invoke(ctx, Expense_CreateExpense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseClient) GetExpenses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetExpensesResponse, error) {
	out := new(GetExpensesResponse)
	err := c.cc.Invoke(ctx, Expense_GetExpenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseClient) DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, opts ...grpc.CallOption) (*DeleteExpenseResponse, error) {
	out := new(DeleteExpenseResponse)
	err := c.cc.Invoke(ctx, Expense_DeleteExpense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseClient) UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...grpc.CallOption) (*UpdateExpenseResponse, error) {
	out := new(UpdateExpenseResponse)
	err := c.cc.Invoke(ctx, Expense_UpdateExpense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpenseServer is the server API for Expense service.
// All implementations must embed UnimplementedExpenseServer
// for forward compatibility
type ExpenseServer interface {
	CreateExpense(context.Context, *CreateExenseRequest) (*CreateExpenseResponse, error)
	GetExpenses(context.Context, *Empty) (*GetExpensesResponse, error)
	DeleteExpense(context.Context, *DeleteExpenseRequest) (*DeleteExpenseResponse, error)
	UpdateExpense(context.Context, *UpdateExpenseRequest) (*UpdateExpenseResponse, error)
	mustEmbedUnimplementedExpenseServer()
}

// UnimplementedExpenseServer must be embedded to have forward compatible implementations.
type UnimplementedExpenseServer struct {
}

func (UnimplementedExpenseServer) CreateExpense(context.Context, *CreateExenseRequest) (*CreateExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExpense not implemented")
}
func (UnimplementedExpenseServer) GetExpenses(context.Context, *Empty) (*GetExpensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpenses not implemented")
}
func (UnimplementedExpenseServer) DeleteExpense(context.Context, *DeleteExpenseRequest) (*DeleteExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExpense not implemented")
}
func (UnimplementedExpenseServer) UpdateExpense(context.Context, *UpdateExpenseRequest) (*UpdateExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExpense not implemented")
}
func (UnimplementedExpenseServer) mustEmbedUnimplementedExpenseServer() {}

// UnsafeExpenseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpenseServer will
// result in compilation errors.
type UnsafeExpenseServer interface {
	mustEmbedUnimplementedExpenseServer()
}

func RegisterExpenseServer(s grpc.ServiceRegistrar, srv ExpenseServer) {
	s.RegisterService(&Expense_ServiceDesc, srv)
}

func _Expense_CreateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServer).CreateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expense_CreateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServer).CreateExpense(ctx, req.(*CreateExenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expense_GetExpenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServer).GetExpenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expense_GetExpenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServer).GetExpenses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expense_DeleteExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServer).DeleteExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expense_DeleteExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServer).DeleteExpense(ctx, req.(*DeleteExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expense_UpdateExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServer).UpdateExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expense_UpdateExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServer).UpdateExpense(ctx, req.(*UpdateExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Expense_ServiceDesc is the grpc.ServiceDesc for Expense service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Expense_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Expense",
	HandlerType: (*ExpenseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExpense",
			Handler:    _Expense_CreateExpense_Handler,
		},
		{
			MethodName: "GetExpenses",
			Handler:    _Expense_GetExpenses_Handler,
		},
		{
			MethodName: "DeleteExpense",
			Handler:    _Expense_DeleteExpense_Handler,
		},
		{
			MethodName: "UpdateExpense",
			Handler:    _Expense_UpdateExpense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expense/expenses.proto",
}
